### ISSUE TITLE
Batched commands missing in ProfiledCommandEnumerable

### ISSUE THREAD

**Issue by kerams** [StackExchange/StackExchange.Redis#2175]
When manually creating and executing a batch of commands, these don't show up after `FinishProfiling`. When I remove the batch and execute them on the database, they do appear.

Is there a technical reason why this isn't implemented or has no one has simply asked for it? To me it seems reasonable to expect batched commands to be included in the profiler.

**Comment by mgravell** [comment]
Sounds like simply an oversight.

**Comment by NickCraver** [comment]
This should be fixed in 2.6.48, was due to a missing overload solved in #2177.

**Comment by kerams** [comment]
I've been on that version since it came out, so I went ahead and double checked the profiler. Still can't see batched commands.

**Comment by kerams** [comment]
I've been on that version since it came out, so I went ahead and double checked the profiler. Still can't see batched commands.

**Comment by NickCraver** [comment]
@kerams ACK - reopening this then!

**Comment by mccow002** [comment]
Any update on this?
