### ISSUE TITLE
IDatabase.StringGetAsync different behaviour in .net 4.6.1 and .net 6.0

### ISSUE THREAD

**Issue by abhisheksingh-ms** [StackExchange/StackExchange.Redis#2516]
My Web API (C#) running on Azure App service is using Azure Redis Cache with NuGet version 2.6.66. and connection string  as {account}.redis.cache.windows.net,ssl=True,password={pwd},abortConnect=false

I have also added ConnectionFailed event  but it is not getting called (nothing written to logs)

`
class WrappedConnectionMultiplexer
{
   public WrappedConnectionMultiplexer(string connectionString, bool preserveAsyncOrder, IMyAppLogger logger)
{
this.connectionMultiplexer = ConnectionMultiplexer.Connect(connectionString);
this.connectionMultiplexer.ConnectionFailed += OnConnectionFailure;
this.logger = logger;
}

//this is not logging anything
private void OnConnectionFailure(object sender, ConnectionFailedEventArgs eventArgs)
{
  // this is ApplicationInsight logger
  this.IMyAppLogger.TrackTrace(eventArgs.Exception?.ToString());
}

//client code to read from cache

WrappedConnectionMultiplexer wrappedConnectionMultiplexer;
if (!myDictionary.TryGetValue(connectionString, out wrappedConnectionMultiplexer))
 {
   wrappedConnectionMultiplexer = new WrappedConnectionMultiplexer(connectionString, preserveAsyncOrder);
   myDictionary.AddOrUpdate(connectionString, (key) => wrappedConnectionMultiplexer, (key, x`) => wrappedConnectionMultiplexer);
 }

var cacheDatabase = await Task.FromResult(wrappedConnectionMultiplexer.GetDatabase());
await cacheDatabase.StringGetAsync(string key);

`

But if the key doesn't exist or account name is incorrect. I see different behavior in .NET framework 4.6.1 and .NET 6.0

.Net framework 4.6.1 StringGetAsync() will immediately return Or connection exception if account is incorrect in connection string.

.net 6.0 StringGetAsync() doesn't return (until the app monitoring code cancel the request after application timeout of 10 sec).

in both .NET versions, StringSetAsync is executed with CommandFlags.FireandForgot and call immediately return.

Question:

1. Is this difference expected or there is different way to use redis in 6.0.
2. why ConnectionFailed event is not called (nothing writtern to AI logs)

**Comment by mgravell** [comment]
2.6.66 is a year old; a number of bugs etc have been fixed in that time -
possibly I wonder if this is related to the GC fix that was in one of them
(I'm not going to click into each to find which exactly).

Try with NuGet latest; if it happens with latest: this might be
interesting. But until you've tested with latest, I'm going to assume it is
already fixed.

**Comment by mgravell** [comment]
Either your server located on the moon, or something is very weird here. Are you creating the multiplexer per call, or is this a pre-existing and long-lived multiplexer instance?

**Comment by NickCraver** [comment]
@abhisheksingh-ms I'm confused on what we're trying to solve here. Is the complaint that it doesn't fail instantly, but should still fail? The .NET 4.6.1 is on 2.1.28 not 2.6.x like earlier comments, so I'm not sure which things we're comparing here.

In more recent versions of the library, when you've set `abortConnect=false` (I can see that's your case by the `aoc: 0`), we'll buffer the command and try for the duration of a timeout while that connection attempts to connect. In both of these cases it looks like you're not connecting and failing which is the real upstream issue, the behavior difference is backlog functionality added in 2.5.x (this doesn't differ between .NET 4.6 and .NET 6.0). If you want to turn this off, you can change the BacklogPolicy on your config to fail immediately, but none of that will solve the "it didn't even connect" issue at hand.
