### ISSUE TITLE
No connection is available to service this operation: EVAL

### ISSUE THREAD

**Issue by sgoky** [StackExchange/StackExchange.Redis#292]
Server Error in '/' Application.

---

No connection is available to service this operation: EVAL
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL

Source Error:
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[RedisConnectionException: No connection is available to service this
operation: EVAL]
   StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl(Message
message, ResultProcessor`1 processor, ServerEndPoint server) +559
   StackExchange.Redis.RedisBase.ExecuteSync(Message message,
ResultProcessor`1 processor, ServerEndPoint server) +119
   StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) +249
   Microsoft.Web.Redis.<>c__DisplayClass4.<Eval>b__3() +52
   Microsoft.Web.Redis.StackExchangeClientConnection.RetryForScriptNotFound(Func`1
redisOperation) +167
   Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1
redisOperation) +227
   Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) +689
   Microsoft.Web.Redis.RedisConnectionWrapper.Set(ISessionStateItemCollection
data, Int32 sessionTimeout) +99
   Microsoft.Web.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(HttpContext
context, String id, SessionStateStoreData item, Object lockId, Boolean
newItem) +1083
   System.Web.SessionState.SessionStateModule.OnReleaseState(Object
source, EventArgs eventArgs) +1021
   System.Web.SessionState.SessionStateModule.OnEndRequest(Object source, EventArgs eventArgs) +208
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
+92
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&
completedSynchronously) +165

How can I fix this?
Thank you.

**Comment by roypun** [comment]
I have the same issue

**Comment by jessek1** [comment]
Got the same error.

No connection is available to service this operation: EVAL

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[RedisConnectionException: No connection is available to service this operation: EVAL]
   StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl(Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:1910
   StackExchange.Redis.RedisBase.ExecuteSync(Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:81
   StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:884
   Microsoft.Web.Redis.<>c__DisplayClass4.<Eval>b__3() in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:117
   Microsoft.Web.Redis.StackExchangeClientConnection.RetryForScriptNotFound(Func`1 redisOperation) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:133
   Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:155
   Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:117
   Microsoft.Web.Redis.RedisConnectionWrapper.TryTakeWriteLockAndGetData(DateTime lockTime, Int32 lockTimeout, Object& lockId, ISessionStateItemCollection& data, Int32& sessionTimeout) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:182
   Microsoft.Web.Redis.RedisSessionStateProvider.GetItemFromSessionStore(Boolean isWriteLockRequired, HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:270
   Microsoft.Web.Redis.RedisSessionStateProvider.GetItemExclusive(HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:190
   System.Web.SessionState.SessionStateModule.GetSessionStateItem() +111
   System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData) +778
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +285
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by gonace** [comment]
We're experiencing the same issue, is this being worked on?

**Comment by jessek1** [comment]
Make sure your web.config is configured properly for the session state provider.

```xml
<sessionState mode="Custom" customProvider="MySessionStateStore">
      <providers>
        <!-- Either use 'connectionString' and provide all parameters as string OR use 'host','port','accessKey','ssl','connectionTimeoutInMilliseconds' and 'operationTimeoutInMilliseconds'. -->
        <!-- 'throwOnError','retryTimeoutInMilliseconds','databaseId' and 'applicationName' can be used with both options. -->
        <!--
          <add name="MySessionStateStore" 
            host = "127.0.0.1" [String]
            port = "" [number]
            accessKey = "" [String]
            ssl = "false" [true|false]
            throwOnError = "true" [true|false]
            retryTimeoutInMilliseconds = "5000" [number]
            databaseId = "0" [number]
            applicationName = "" [String]
            connectionTimeoutInMilliseconds = "5000" [number]
            operationTimeoutInMilliseconds = "1000" [number]
            connectionString = "<Valid StackExchange.Redis connection string>" [String]
            loggingClassName = "<Assembly qualified class name that contains logging method specified below>" [String]
            loggingMethodName = "<Logging method should be defined in loggingClass. It should be public, static, does not take any parameters and should have a return type of System.IO.TextWriter.>" [String]
          />
        -->
        <add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="127.0.0.1" port="6379" accessKey="" ssl="false" />
      </providers>
    </sessionState>
```

**Comment by SushantKadam008** [comment]
HI Jessek1,
From today morning I am also facing the same issue.
My code in local environment was working till yesterday .
Today when I run in VS I get the above error.
I tried all the possible solution but it doe not work.

Please help.

Regards,
Sushant Kadam

**Comment by haribansh** [comment]
Hi, everyone. Do we have any update on it? I am also facing same issue after reloading my desktop and VS.

Thanks for your help in advance.

**Comment by Ghosts** [comment]
Not sure if it'll work fro you guys, but on my end I fixed this by clearing browser cache itself. You can emulate it without going through the trouble by attempting a connection through an incognito window.

**Comment by YannikG** [comment]
Hello everyone

I faced this issue today and the fix for me was to generate a new primary connection string in Azure.
Make sure you're using the correct password and the correct syntax.

For more read the docs :1st_place_medal: 

Hope my answer was helpful for someone

**Comment by Anufriev** [comment]
I also faced this issue today. I rebooted azure redis service but it didn't solve this. 
I tried to use secondary key and it helped me.

**Comment by NickCraver** [comment]
There are a few issues tracking this, and the ones here align with those long-since solved. Going to close this out to consolidate and cleanup.
