### ISSUE TITLE
Restoring connection to redis

### ISSUE THREAD

**Issue by shvez** [StackExchange/StackExchange.Redis#38]
Hi, there.

I use StackExchange.Redis.1.0.281.0
It is turned out that lib can't restore connection to redis in some cases.

My application executes next code every few seconds

```
try
{
      var server = this.application.Multiplexer.GetServer(RedisServerAddress);
      var keys = server.Keys(Properties.Settings.Default.BackendRedisDBId);
...............
}
catch(Exception e)
{
  //log exception
}
```

In order to check how this code works when connection lost and restored, i just stopped Redis and started it again. Most of the time connection restored, but some times does not. The code above fails with exception until i restart Redis again. After restart lib restores connection.

I create ConnectionMultiplexer next way

```
 var config = ConfigurationOptions.Parse(RedisServerAddress);

 config.KeepAlive = 5;
 config.SyncTimeout = 1000;
 config.AbortOnConnectFail = false;
 config.AllowAdmin = true;

 var muxer = ConnectionMultiplexer.Connect(config);

 muxer.ConfigurationChanged += (sender, args) => log.DebugFormat("ConfigurationChanged with endpoint: {0}", args.EndPoint);
 muxer.ConfigurationChangedBroadcast += (sender, args) => log.DebugFormat("ConfigurationChangedBroadcast with endpoint: {0}", args.EndPoint);
 muxer.ConnectionFailed += (sender, args) => log.DebugFormat("ConnectionFailed with args: {0}", args.Exception.Message);
 muxer.ConnectionRestored += (sender, args) => log.DebugFormat("ConnectionRestored with args: {0}", args.EndPoint);
 muxer.ErrorMessage += (sender, args) => log.DebugFormat("ErrorMessage with args: {0}", args.Message);
 muxer.HashSlotMoved += (sender, args) => log.DebugFormat("HashSlotMoved with args: {0}", args.NewEndPoint);
 muxer.InternalError += (sender, args) => log.DebugFormat("InternalError with args: {0}", args.Exception);
```

What information yet should i provide in order to help find reason?

**Comment by nmehlei** [comment]
I am still observing this problem, although it only occurs relatively rare (gut feeling: every 8-16 days). Sometimes "No connection is available to service this operation" just occurs and then resumes working ( #193 ) or the connection never recovers and it remains in this state indefinitely (=until app restarts), as is described in this ticket. Although it is now very rare, it doesn't seem like this issue is completely resolved.

**Comment by volkovku** [comment]
I confirm this problem does not solved.
The first error is: StackExchange.Redis.RedisConnectionException: UnableToResolvePhysicalConnection on HSET
After that exception changes to: No connection is available to service this operation
Connection never recovers until application was restarted.

**Comment by mehdymohajery** [comment]
the issue still exists in version 1.0.316.0

**Comment by davidbetz** [comment]
More information: confirmed same problem on 1.0.316.0 using Azure. It's very intermited, but solid for me for the past hour. This is not from a debugger timeout. This is on the StringGetAsync(String) call.

**Comment by NickCraver** [comment]
Re-opening this and merging in #81

**Comment by gsogol** [comment]
Getting this in Azure still.

**Comment by abhi004** [comment]
Still issue exits ..I have checked it today its been a long now

**Comment by RemiBou** [comment]
Issue still exists, and I'm in Azure, is this issue only on azure ? Maybe it's not a client thing

**Comment by yechongbo** [comment]
Same error here, on Windows Azure and Version=1.0.316.0

**Comment by LightCrystal** [comment]
Getting this 2 or 3 times a day, every time I need to redeploy the whole Azure cloud service. I'm switching to Service Fabric Stateful service, I found Azure Redis Cache totally unreliable for high  throughput projects.

**Comment by Plasma** [comment]
I've hardly had this problem now, its only been during Azure cache maintenance events.

My recommendation is to ensure:
1) Your web/worker role (whatever is sending the data) is not CPU or network bound
2) Your redis cache instance is of a good enough size to sustain the workload its getting
3) Check your not sending/receiving huge amounts of data (eg sustained 10MB/sec or something) that could cause network timeouts

The redis cache metrics/advisor menu in the azure portal should hopefully provide some insight if you're reaching some of those limits.

**Comment by Misterhex** [comment]
Getting this as well from using windows redis. It seems azure redis cache is also running windows redis. 

Does anyone get this issue when running against the Linux variant?

Does it make sense to have a pool of connection multiplexer, and checking the connection status before using it?

**Comment by mehdyhaghy** [comment]
my best guess: 
it happens when you store large key values in redis.
for instance we are using redis as asp.net session store and 
I've seen Microsoft Report Viewer storing session keys as large as 600 KB.
install RedisDesktopManager and navigate stored keys in redis.

**Comment by AndreiShenets** [comment]
We also see the same issue. 
**What I have:**
Two redis instances without sentinel with manual switching of master/slave
Redis2 is master
Redis1 is slave of Redis1
Console application which checks if redis1 is not a slave of redis2 then forces slave of.
**What I do:**
I restart Redis2. 
**What I see**
Replication is broken on this step;
redis-cli info for Redis2 shows that it's still a master but has no slaves
redis-cli info for Redis1 shows that it's still a slave **but the master for it localhost 6379 and NOT Redis2**

So I guess there is something wrong with info command and state caching.

**Comment by Misterhex** [comment]
We recently moved from windows redis to running on linux, we did not experience the issue anymore.

**Comment by kent3513** [comment]
I got the same issue on the linux.
My Redis servers are Cluster. 
After servers decrease memory from 4G to 2G,
The exception : "No connection is available to service this operation" occurs usually a day.

**Comment by shvez** [comment]
it would be good to know what version is used. 
i assume this bug was fixed in last version

**Comment by rbbarranco** [comment]
We still experience this issue on 1.1.603. We do get "StackExchange.Redis.RedisConnectionException : No connection is available to service this operation:" when doing migration but our services recover after.

But on rare occasions, we get a "StackExchange.Redis.RedisConnectionException : UnableToResolvePhysicalConnection" error. And when it does, some our services fail to recover. Strange thing is that not all of our services fail to recover, only 1 or 2 do not. And it's not the same set of services that fail to recover when we get the exception, it's random. 

We don't use Redis Cluster. We have 6 servers in Linux.

**Comment by hfar0k** [comment]
Getting the same issue when switched to StackExchange, error No connection is available to service this operation:" appears after restart of master node. The only way to fix that atm is to restart all slaves and recycle app pool for client to reconnect.

**Comment by minjie-kooboo** [comment]
We still have the same problem in Azure platform.
StackExchange.Redis: 1.2.6

**Comment by PaitoAnderson** [comment]
@minjie-kooboo We had the same issue with the Azure Redis Cache service, I ended up just using a Azure Linux VM and installing redis and the issue went away.

**Comment by nguyenchiencong** [comment]
Still happen on Azure

**Comment by michaellandi** [comment]
I am also getting this issue.  Im using Redis in Linux containers. 

When a container hosting Redis master node is lost unexpectedly (shutdown for example) we do not see the ConnectionFailed event fire.  It only fires when the node comes back up and restores (ConnectionRestored).  It's almost as if at that SE.Redis realizes that the particular node was down.

This occurs even with KeepAlive intervals set.  Not sure how SE.Redis wouldn't know a node is down if sending keep alives....

**Comment by lciocci** [comment]
We're also experiencing intermittent UnableToResolvePhysicalConnection issues. Our applications are deployed to Azure, and we're currently running an older version - 1.2.1. Once the issue occurs it continues to occur until the service is restarted. Anyone know if this issue been fixed in 1.2.6?

**Comment by NickCraver** [comment]
@lciocci Yep, lots of fixes since then, especially around reconnects. There aren't any breaking changes, so an upgrade is safe to do.

**Comment by ryankelley** [comment]
@lciocci @NickCraver We are still experiencing the same issue with Azure Redis Cache, with our app on VM's and App Services.  We have been using 1.2.6 for several months and have been experiencing this intermittently over that time.

**Comment by Plasma** [comment]
If you haven't already done it, I recommend setting ``options.KeepAlive = 10;`` to ensure on Azure the redis connection is kept alive.

Azure LB will disconnect idle sockets after 4 min by default, which could lead to issues.

**Comment by mgravell** [comment]
Closing; please see https://github.com/StackExchange/StackExchange.Redis/issues/871

**Comment by n1l** [comment]
> If you haven't already done it, I recommend setting `options.KeepAlive = 10;` to ensure on Azure the redis connection is kept alive.
> 
> Azure LB will disconnect idle sockets after 4 min by default, which could lead to issues.

Hi, can you please describe how `keepAlive = 10`, and default keepAlive - 60 are related here? Because 10 and 60 are both less then 4 minutes?

**Comment by xdrnc** [comment]
For anyone who managed to reproduce the NullReferenceException from **WriteHeader(RedisCommand command, int arguments)**, does anyone know which object causes the null? Multiplexer? Multiplexer.CommandMap? or Bridge?
